name: DeathLockout
main: org.kitteh.deathlockout.DeathLockout
author: mbaxter
version: '${project.version}'
permissions:
   deathlockout.exempt:
       description: Exempt from being kicked on death
       default: false