name: DeathLockout
main: org.kitteh.deathlockout.DeathLockout
author: mbaxter
version: 1.1
permissions:
   deathlockout.exempt:
       description: Exempt from being kicked on death
       default: false